name: carestack-os
description: Custom Fedora Kinoite image for Carestack dental practices

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42

modules:
  - type: command
    source: local
    description: "🧪 Debug: List contents of /tmp/files"
    command: "find /tmp/files || echo '/tmp/files not found'"

  - type: files
    source: local

  - type: rpm-ostree
    source: local
    packages: packages.json

  - type: yafti
    source: local
    manifest: yafti.yml

  - type: default-flatpaks
    source: local
    include: flatpaks.json
