name: carestack-os
description: Custom Fedora Kinoite image for Carestack dental practices
base-image: ghcr.io/ublue-os/kinoite-main
flatpaks: flatpaks.json
packages: packages.json
install:
  - yafti
  - plymouth-theme
  - wallpaper
  - kde-config