name: carestack-os
description: Custom Fedora Kinoite image for Carestack dental practices

image-version: image-versions.yaml

modules:
  - type: files
    source: files

  - type: system-packages
    packages: packages.json

  - type: flatpaks
    manifest: flatpaks.json

  - type: yafti
    manifest: yafti.yaml

  - type: plymouth
    name: carestack-os

  - type: wallpaper
    path: usr/share/wallpapers/CarestackOS/default.jpg

  - type: skel
    paths:
      - etc/skel/.config
