name: carestack-os
description: Custom Fedora Kinoite image for Carestack dental practices

base-image: ghcr.io/ublue-os/kinoite
image-version: image-versions.yaml

modules:
  - type: files
    source: files

  - type: rpm-ostree
    source: local
    packages: packages.json

  - type: yafti
    source: local

  - type: default-flatpaks
    source: local
    include: flatpaks.json
